version: '3'
services:
  app:
    image: node:14.1.0-alpine
    restart: unless-stopped
    working_dir: /app
    # ports:
    # - '${HTTP_PORT}:1337'
    volumes:
      - ./:/app
      # - ${OUTPUT_VOLUME}/log/nginx:/var/log/nginx
    # command: ./start.sh
    networks:
      - default
  db:
    image: mongo:4.4.0
    restart: unless-stopped
    # working_dir: /app
    ports:
      - '${DB_PORT}:27017'
    # volumes:
    # - ./:/app
    # - ${OUTPUT_VOLUME}/log/nginx:/var/log/nginx
    # command: ./start.sh
    networks:
      - default
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - '8080:15672'
      - '5672:5672'
    networks:
      - default
