version: '3'
services:
  db:
    image: mongo:4.4.0
    restart: unless-stopped
    ports:
      - '${DB_PORT}:27017'
    networks:
      - default
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=secret
    ports:
      - '8080:15672'
      - '5672:5672'
    networks:
      - default
